 # This workflow deploys the site to an S3 bucket and invalidates the CloudFront distribution. May 2025
 name: Deploy My Portfolio Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Deploy My Portfolio Site to S3 and invalidate CloudFront cache
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1  # my region Ireland

      - name: Build and Deploy to S3
        run: |
          aws s3 sync . s3://amzn-s3-my-site-2025 --delete 

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E2LY7P7UN248DZ --paths "/*"